// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2bawisXR4MHzhCnIDMLpA6fgplfz4g4I',
    appId: '1:104212408664:web:c4e11fe524c7811e691d2d',
    messagingSenderId: '104212408664',
    projectId: 'flutterrusumeapp',
    authDomain: 'flutterrusumeapp.firebaseapp.com',
    storageBucket: 'flutterrusumeapp.appspot.com',
    measurementId: 'G-8TKF2RFRQR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCovJCzu4sp_-aFtvAK62tAaAGhwc8umWM',
    appId: '1:104212408664:android:2973579ec661269c691d2d',
    messagingSenderId: '104212408664',
    projectId: 'flutterrusumeapp',
    storageBucket: 'flutterrusumeapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-jxmlf7fI75mwOK3IwraxxCy90X1kKK8',
    appId: '1:104212408664:ios:507e7a1225590581691d2d',
    messagingSenderId: '104212408664',
    projectId: 'flutterrusumeapp',
    storageBucket: 'flutterrusumeapp.appspot.com',
    iosBundleId: 'com.example.rusumeBuilderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-jxmlf7fI75mwOK3IwraxxCy90X1kKK8',
    appId: '1:104212408664:ios:3484f0acd03784a4691d2d',
    messagingSenderId: '104212408664',
    projectId: 'flutterrusumeapp',
    storageBucket: 'flutterrusumeapp.appspot.com',
    iosBundleId: 'com.example.rusumeBuilderApp.RunnerTests',
  );
}
